ConferenceApp/Models/Talk.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ConferenceApp.Models
{
    public class Talk : Event
    {
        [Required]
        public string Topic { get; set; }

        public List<EventTag> EventTags { get; set; }
        public string Exhibitor { get; set; }
    }
}

ConferenceApp/Controllers/TalkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ConferenceApp.Data;
using ConferenceApp.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ConferenceApp.Controllers
{
    public class TalkController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TalkController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Talk
        public async Task<IActionResult> Index()
        {
            return View(await _context.Talks.ToListAsync());
        }

        // GET: Talk/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var talk = await _context.Talks
                .FirstOrDefaultAsync(m => m.Id == id);
            if (talk == null)
            {
                return NotFound();
            }
            var currentUserId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var isAssistant = await _context.Roles.Where(x => (x.UserId == currentUserId && x.EventId == talk.Id && x.Name == "attendant")).ToListAsync();

            int assisting = isAssistant.Count;
            ViewBag.assisting = assisting;

            var tagNames = new List<String>();
            var joinedTags = "";
            var eventTags = await _context.EventTags.Where(x => (x.EventId == talk.Id)).ToListAsync();
            if (eventTags.Count > 0)
            {
                foreach (var et in eventTags)
                {
                    var tag = await _context.Tags.FirstOrDefaultAsync(x => x.Id == et.TagId);
                    tagNames.Add("<button type='button' class='btn btn-outline-secondary'>"+tag.Name+"</button>");
                }
                joinedTags = String.Join(" ", tagNames);
            }
            ViewBag.joinedTags = joinedTags;

            var room = await _context.Rooms.FindAsync(@talk.RoomId);
            var centre = await _context.EventCentres.FindAsync(room.EventCentreId);
            var version = await _context.ConferenceVersions.FindAsync(@talk.ConferenceVersionId);
            var conference = await _context.Conferences.FindAsync(version.ConferenceId);

            var sponsorships = await _context.Sponsorships.Where(x => x.ConferenceVersionId == version.Id).ToListAsync();
            var sponsors = new List<object>();
            foreach (var member in sponsorships)
            {
                var s = await _context.Sponsors.FindAsync(member.SponsorId);
                sponsors.Add(s.Name);
            }

            var assistantRoles = await _context.Roles.Where(x => x.EventId == @talk.Id && x.Name == "attendant").ToListAsync();
            var assistants = new List<object>();
            // foreach (var member in assistantRoles)
            // {
            //     var a = await _context.Users.FindAsync(member.UserId);
            //     assistants.Add(a.Email);
            // }

            var fileDescription = "";
            if (talk.FileId > 0)
            {
                var file = await _context.Files.FirstOrDefaultAsync(x => x.Id == talk.FileId);
                if (file != null)
                {
                    fileDescription = file.Description;
                }
            }
            
            var exhibitor = await _context.Users.FindAsync(@talk.Exhibitor);
            
            ViewBag.Exhibitor = exhibitor;

            var EventAssistance = await _context.Roles.Where(x => x.EventId == talk.Id && x.Name == "attendant").CountAsync();

            var FeedbackCategories = await _context.FeedbackCategories.ToListAsync();
            var Feedbacks = await _context.Feedbacks.Where(x => x.EventId == talk.Id).ToListAsync();

            var FeedbackAveragePerCategory = new List<object>();
            var FeedbackCategoryName = new List<object>();

            foreach (var Category in FeedbackCategories)
            {
                FeedbackCategoryName.Add(Category.Name);
                var FeedbacksScopesOfEventAndCategory = await _context.FeedbackScopes.Where(fs => Feedbacks.Any(f => fs.FeedbackId == f.Id && fs.FeedbackCategoryId == Category.Id)).ToListAsync();

                if (FeedbacksScopesOfEventAndCategory.Count() >= 1)
                {
                    FeedbackAveragePerCategory.Add(FeedbacksScopesOfEventAndCategory.Average(f => f.Grade).ToString());
                }
                else
                {
                    FeedbackAveragePerCategory.Add("No hay evaluaciones todavía");
                }
            }
            ViewBag.permision = false;

            var conferenceVersion = await _context.ConferenceVersions.FindAsync(@talk.ConferenceVersionId);
            var bigConference = await _context.Conferences.FindAsync(conferenceVersion.ConferenceId);
            var adminList = await _context.Admins.Where(x => x.UserId == currentUserId).ToListAsync();
            if (adminList.Count > 0)
            {
                ViewBag.permision = true;
            }

            if (bigConference.OrganizerId == currentUserId)
            {
                ViewBag.permision = true;
            }
            var organizer = await _context.Users.FindAsync(bigConference.OrganizerId);
            ViewBag.organizer = organizer;
            ViewBag.feedback = await _context.Feedbacks.FirstOrDefaultAsync(f => f.UserId == currentUserId && f.EventId == @talk.Id);

            ViewBag.roomName = room.Name;
            ViewBag.centreName = centre.Name;
            ViewBag.location = centre.Location;
            ViewBag.version = version;
            ViewBag.conference = conference;
            ViewBag.assistants = assistants;
            ViewBag.sponsors = sponsors;
            ViewBag.fileDescription = fileDescription;
            ViewBag.EventAssistance = EventAssistance;
            ViewBag.FeedbackCategoryName = FeedbackCategoryName;
            ViewBag.FeedbackAveragePerCategory = FeedbackAveragePerCategory;

            var isOrganizer = currentUserId == conference.OrganizerId;
            ViewBag.isOrganizer = isOrganizer;
            
            var admin = await _context.Admins.FirstOrDefaultAsync(x => x.UserId == currentUserId);
            var isAdmin = admin != null;
            ViewBag.isAdmin = isAdmin;

            return View(talk);
        }

        // GET: Talk/Create
        public async Task<IActionResult> Create(int? conferenceVersionId)
        {
            var conferenceVersions = conferenceVersionId == null
                ? await _context.ConferenceVersions.ToListAsync()
                : await _context.ConferenceVersions.Where(x => x.Id == conferenceVersionId).ToListAsync();

            var rooms = await _context.Rooms.Where(x => x.EventCentreId == conferenceVersions[0].EventCentreId).ToListAsync();

            List<object> versions = new List<object>();
            foreach (var member in conferenceVersions)
                versions.Add( new {
                    Id = member.Id,
                    Name = (await _context.Conferences.FindAsync(member.ConferenceId)).Name + " (versión " + member.Number + ")"
                } );

            var tags = await _context.Tags.ToListAsync();
            var availableTags = tags.Select(tag => new CheckBoxItem() {TagId = tag.Id, Title = tag.Name, IsChecked = false}).ToList();
            
            var users = await _context.Users.ToListAsync();
            var userList = new List<object>();
            foreach (var user in users)
            {
                userList.Add(user);
            }
            ViewBag.Exhibitors = new SelectList(userList , "Id", "Email");
            this.ViewData["ConferenceVersions"] = new SelectList(versions, "Id", "Name");
            this.ViewData["Rooms"] = new SelectList(rooms, "Id", "Name");
            this.ViewData["AvailableTags"] = new List<CheckBoxItem>(availableTags);
            return View();
        }

        // POST: Talk/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Topic,Id,Name,StartDate,EndDate,ConferenceVersionId,RoomId,ExhibitorId,AvailableTags")] Talk talk)
        {

            var conferenceVersion = await _context.ConferenceVersions.Where(x => x.Id == talk.ConferenceVersionId).FirstOrDefaultAsync();
            var events = await _context.Events.Where(x => x.ConferenceVersionId == conferenceVersion.Id).ToListAsync();
            var room = await _context.Rooms.Where(x => x.Id == talk.RoomId).FirstOrDefaultAsync();
            var isOccupied = 0;

            var sharedRoomEvents = await _context.Events.Where(x => x.ConferenceVersionId == talk.ConferenceVersionId && x.RoomId == talk.RoomId).ToListAsync();
            foreach (var even in sharedRoomEvents)
            {
                if (talk.StartDate <= even.StartDate && talk.EndDate >= even.StartDate)
                {
                    isOccupied = 1;
                }
                else if (talk.StartDate <= even.EndDate && talk.EndDate >= even.EndDate)
                {
                    isOccupied = 1;
                }
                else if (talk.StartDate >= even.StartDate && talk.EndDate <= even.EndDate)
                {
                    isOccupied = 1;
                }
                else if (talk.StartDate <= even.StartDate && talk.EndDate >= even.EndDate)
                {
                    isOccupied = 1;
                }
                if (isOccupied == 1)
                {
                    TempData["RoomError"] = "Valor Temporal";

ConferenceApp/Views/Talk/Create.cshtml
@model ConferenceApp.Models.Talk

@{
    ViewData["Title"] = "Nueva Charla";
}

<h1>Nueva charla</h1>

<h4>Info</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Título</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Topic" class="control-label">Tema</label>
                <input asp-for="Topic" class="form-control" />
                <span asp-validation-for="Topic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Exhibitor" class="control-label">Expositor</label>
                <select asp-for="Exhibitor" class="form-control" asp-items="ViewBag.Exhibitors"></select>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label">Inicio</label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label">Fin</label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConferenceVersionId" class="control-label">Conferencia</label>
                <select asp-for="ConferenceVersionId" class ="form-control" asp-items="ViewBag.ConferenceVersions"></select>
            </div>
            <div class="form-group">
                <label asp-for="RoomId" class="control-label">Sala</label>
                <select asp-for="RoomId" class ="form-control" asp-items="ViewBag.Rooms"></select>
            </div>
            <div class="form-group">
             <label class="control-label">Tags</label>
                <table>
                    @for (var i = 0; i < ViewBag.AvailableTags.Count; i++)
                    {
                        <tr>
                            <td>
                                <input type="checkbox" asp-for="AvailableTags[i].IsChecked"  />
                                <label asp-for="AvailableTags[i].IsChecked" style="color:DodgerBlue;">#@ViewBag.AvailableTags[i].Title</label>
                            </td>
                            <td>
                                <input type="hidden" asp-for="AvailableTags[i].TagId" value=@ViewBag.AvailableTags[i].TagId/>
                                <input type="hidden" asp-for="AvailableTags[i].Title" value=@ViewBag.AvailableTags[i].Title />
                            </td>
                        </tr>
                    }
                </table>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Event" asp-action="Index">Ver todos los eventos</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ConferenceApp/Views/Talk/Delete.cshtml
@model ConferenceApp.Models.Talk

@{
    ViewData["Title"] = "Eliminar Charla";
}

<h1>Eliminar charla</h1>
<div>
    <h4>Charla</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Topic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Topic)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-controller="Event" asp-action="Index">Ver todos los eventos</a>
    </form>
</div>

ConferenceApp/Views/Talk/Details.cshtml
@model ConferenceApp.Models.Talk

@{
    ViewData["Title"] = "Charla";
}
@if (TempData["AssistError"] != null)
{
    <div class="alert alert-danger alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        @TempData["AssistError"]
    </div>
}

<div class="row">
    <div class="col-sm-3">Organiza: @ViewBag.organizer</div>
    <div class="col-sm-3">
        Patrocina:
        @foreach (var item in ViewBag.sponsors)
        {
            <span>@item | </span>
        }
    </div>
    @if (ViewBag.permision == true)
    {

        <div class="col-sm-6" style="text-align: right;">
            <a asp-controller="Talk" asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |
            <a asp-controller="Sponsorship" asp-action="Create" asp-route-conferenceVersionId="@ViewBag.version.Id" asp-route-eventId="@Model.Id">Agregar patrocinador</a> |
            <a asp-controller="Talk" asp-action="Delete" asp-route-id="@Model.Id">Eliminar</a>
        </div>
    }
    
</div>
<hr/>
<div class="row">
    <br/>
    <div class="col-sm-2">
        <img alt="calendar" src="https://cdn4.iconfinder.com/data/icons/small-n-flat/24/calendar-512.png" style="width: 150px;">
    </div>
    <div class="col-sm-6">
        <div class="row">
            <h6><b>Desde: </b>@Model.StartDate.ToString("dddd d 'de' MMMM yyyy, h:mm tt", new System.Globalization.CultureInfo("es-ES"))</h6>
        </div>
        <div class="row">
            <h6><b>Hasta: </b>@Model.EndDate.ToString("dddd d 'de' MMMM yyyy, h:mm tt", new System.Globalization.CultureInfo("es-ES"))</h6>
        </div>
        <div class="row">
            <h1>@Html.DisplayFor(model => model.Name)</h1>
        </div>
        <div class="row">
            <h5>Charla</h5>
        </div>
    </div>
    <div class="col-sm-4">
       @if (DateTime.Now > Model.EndDate)
       {
           if (ViewBag.assisting == 0)
           {
               <i>Este evento ya finalizó.</i>
           }
           else
           {
               if (ViewBag.feedback == null)
                {
                    <i>Este evento ya finalizó. Dado que asististe, puedes evaluarlo.</i>
                    <a asp-controller="Feedback" asp-action="Create" asp-route-eventId="@Model.Id" style="text-decoration: none; color: white;">
                        <button type="button" class="btn btn-primary" style="width: 100%;">Evaluar</button>
                    </a>
                }
                else
                {
                    <i>Este evento ya finalizó y mandaste tu <a asp-controller="Feedback" asp-action="Details" asp-route-id="@ViewBag.feedback.Id">evaluación</a>.</i>
                }
           }
       }
       else
       {
           @if (ViewBag.assisting == 0)
           {
               <a asp-action="AddAssistant" asp-route-eventId="@Model.Id" style="text-decoration: none; color: white;">
                   <button type="button" class="btn btn-success" style="width: 100%;">Asistir</button>
               </a>
           }
           else
           {
               <a asp-action="RemoveAssistant" asp-route-eventId="@Model.Id" style="text-decoration: none; color: white;">
                   <button type="button" class="btn btn-primary" style="width: 100%;">Dejar de asistir</button>
               </a>
           }
           <br>
           <br>
           <a asp-controller="Notification" asp-action="Create" asp-route-eventId="@Model.Id" asp-route-conferenceVersionId="@Model.ConferenceVersionId" asp-route-conferenceName="@ViewBag.conference.Name" asp-route-eventName="
@Model.Name" asp-route-conferenceVersionNumber="@ViewBag.version.Number" asp-route-eventType="Talk" style="text-decoration: none; color: white;">
               <button type="button" class="btn btn-primary" style="width: 100%;">Enviar Notificacion</button>
           </a>
       }
    </div>
</div>
<hr/>
<div class="row">
    <div class="col-sm-8">
        @Html.Raw(ViewBag.joinedTags)
    </div>
    <div class="col-sm-4">
        @ViewBag.centreName - <a asp-controller="Room" asp-action="Details" asp-route-id="@Model.RoomId">@ViewBag.roomName</a> <br/>
        <img alt="calendar" src="https://www.connectsafely.org/wp-content/uploads/Location-pin.png" style="width: 25px;">
        @ViewBag.location
    </div>
</div>
<hr/>

<div class="row">
    <div class="col-sm-8">
        <h5>Más información</h5>
        <dl class="row">
            <dt class = "col-sm-4">
                Tema
            </dt>
            <dd class = "col-sm-8">
                @Html.DisplayFor(model => model.Topic)
            </dd>
            <dt class = "col-sm-4">
                Expositor
            </dt>
            <dd class = "col-sm-8">
                @ViewBag.Exhibitor
            </dd>
            <dt class = "col-sm-4">
                Material Complementario
            </dt>
             <dd class = "col-sm-8">
                @ViewBag.fileDescription
            </dd>
            <dt class = "col-sm-4">

            </dt>
             @if (Model.FileId > 0)
             {

                 if (Model.EndDate < DateTime.Now)
                {
                    <a asp-controller="File" asp-action="Download" asp-route-fileId="@Model.FileId" style="text-decoration: none; color: white;">
                        <button type="button" class="btn btn-success" style="width: 100%;">Descargar</button>
                    </a>
                }
                else
                {
                    <dd class="col-sm-8">
                        <i>Disponible para descargar cuando termine la charla</i>
                    </dd>
                }
            }
            else
            {
                <a asp-controller="File" asp-action="Create" asp-route-eventId="@Model.Id" style="text-decoration: none; color: white;">
                    <button type="button" class="btn btn-primary" style="width: 100%;">Subir material complementario</button>
                </a>
            }
        </dl>
    </div>
    <div class="col-sm-4">
        Conferencia <a asp-controller="Conference" asp-action="Details" asp-route-id="@ViewBag.conference.Id">@ViewBag.conference.Name</a>
        (versión <a asp-controller="ConferenceVersion" asp-action="Details" asp-route-id="@Model.ConferenceVersionId">@ViewBag.version.Number</a>)
    </div>
</div>
<hr/>
<div class="row">
    <div class="col-sm-8">
        <h5>Asistentes</h5>
        <dl class="row">
            <dt class = "col-sm-4">
                Cantidad
            </dt>
            <dd class = "col-sm-8">
                @ViewBag.EventAssistance
            </dd>
        </dl>
    </div>
    <div class="col-sm-4"></div>
</div>
<hr/>
<div class="row">
    <div class="col-sm-8">
        <h5>Estadísticas</h5>
        @for (var i = 0; i < ViewBag.FeedbackCategoryName.Count; i++)
        {
            <dl class="row">
                <dt class = "col-sm-4">
                    @ViewBag.FeedbackCategoryName[i]
                </dt>
                <dd class = "col-sm-8">
                    @ViewBag.FeedbackAveragePerCategory[i]
                </dd>
            </dl>
        }
    </div>
    <div class="col-sm-4"></div>
</div>

ConferenceApp/Views/Talk/Edit.cshtml
@model ConferenceApp.Models.Talk

@{
    ViewData["Title"] = "Editar Charla";
}

<h1>Editar</h1>

<h4>Charla</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">Título</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Topic" class="control-label">Tema</label>
                <input asp-for="Topic" class="form-control" />
                <span asp-validation-for="Topic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Exhibitor" class="control-label">Expositor</label>
                <select asp-for="Exhibitor" class="form-control" asp-items="ViewBag.Exhibitors"></select>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label">Inicio</label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label">Fin</label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoomId" class="control-label">Sala</label>
                <select asp-for="RoomId" class ="form-control" asp-items="ViewBag.Rooms"></select>
            </div>
            <input type="hidden" asp-for="ConferenceVersionId" />
            <input type="hidden" asp-for="FileId" value="@Model.FileId"/>
            <div class="form-group">
             <label class="control-label">Tags</label>
                <table>
                    @for (var i = 0; i < ViewBag.AvailableTags.Count; i++)
                    {
                        <tr>
                            <td>
                                <input type="checkbox" asp-for="AvailableTags[i].IsChecked" checked=@ViewBag.AvailableTags[i].IsChecked />
                                <label asp-for="AvailableTags[i].IsChecked" style="color:DodgerBlue;">#@ViewBag.AvailableTags[i].Title</label>
                            </td>
                            <td>
                                <input type="hidden" asp-for="AvailableTags[i].TagId" value=@ViewBag.AvailableTags[i].TagId/>
                                <input type="hidden" asp-for="AvailableTags[i].Title" value=@ViewBag.AvailableTags[i].Title />
                            </td>
                        </tr>
                    }
                </table>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Event" asp-action="Index">Ver todos los eventos</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ConferenceApp/Views/Talk/Index.cshtml
@model IEnumerable<ConferenceApp.Models.Talk>

@{
    ViewData["Title"] = "Charlas";
}

<h1>Charlas</h1>

<p>
    <a asp-action="Create">Agregar nueva</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Nombre
            </th>
            <th>
                Tema
            </th>
            <th>
                Inicio
            </th>
            <th>
                Fin
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Topic)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Ver</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>