ConferenceApp/Models/FoodService.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ConferenceApp.Models
{
    public class FoodService : Event
    {
        [Required]
        public string Category { get; set; }
        
        public ICollection<MenuOption> MenuOptions { get; set; }
    }
}

ConferenceApp/Controllers/FoodServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ConferenceApp.Data;
using ConferenceApp.Models;

namespace ConferenceApp.Controllers
{
    public class FoodServiceController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FoodServiceController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: FoodService
        public async Task<IActionResult> Index()
        {
            return View(await _context.FoodServices.ToListAsync());
        }

        // GET: FoodService/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var foodService = await _context.FoodServices
                .FirstOrDefaultAsync(m => m.Id == id);
            if (foodService == null)
            {
                return NotFound();
            }
            var currentUserId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var isAssistant = await _context.Roles.Where(x => (x.UserId == currentUserId && x.EventId == foodService.Id && x.Name == "attendant")).ToListAsync();

            int assisting = isAssistant.Count;
            ViewBag.assisting = assisting;

            var room = await _context.Rooms.FindAsync(@foodService.RoomId);
            var centre = await _context.EventCentres.FindAsync(room.EventCentreId);
            var version = await _context.ConferenceVersions.FindAsync(@foodService.ConferenceVersionId);
            var conference = await _context.Conferences.FindAsync(version.ConferenceId);

            var sponsorships = await _context.Sponsorships.Where(x => x.ConferenceVersionId == version.Id).ToListAsync();
            var sponsors = new List<object>();
            foreach (var member in sponsorships)
            {
                var s = await _context.Sponsors.FindAsync(member.SponsorId);
                sponsors.Add(s.Name);
            }

            var assistantRoles = await _context.Roles.Where(x => x.EventId == @foodService.Id && x.Name == "attendant").ToListAsync();
            var assistants = new List<object>();
            // foreach (var member in assistantRoles)
            // {
            //     var a = await _context.Users.FindAsync(member.UserId);
            //     assistants.Add(a.Email);
            // }

            var menus = await _context.MenuOptions.Where(x => x.FoodServiceId == @foodService.Id).ToListAsync();

            var EventAssistance = await _context.Roles.Where(x => x.EventId == foodService.Id && x.Name == "attendant").CountAsync();

            var FeedbackCategories = await _context.FeedbackCategories.ToListAsync();
            var Feedbacks = await _context.Feedbacks.Where(x => x.EventId == foodService.Id).ToListAsync();

            var FeedbackAveragePerCategory = new List<object>();
            var FeedbackCategoryName = new List<object>();

            foreach (var Category in FeedbackCategories)
            {
                if (Category.Name != "Expositor(es)")
                {
                    FeedbackCategoryName.Add(Category.Name);
                    var FeedbacksScopesOfEventAndCategory = await _context.FeedbackScopes.Where(fs => Feedbacks.Any(f => fs.FeedbackId == f.Id && fs.FeedbackCategoryId == Category.Id)).ToListAsync();

                    if (FeedbacksScopesOfEventAndCategory.Count() >= 1)
                    {
                        FeedbackAveragePerCategory.Add(FeedbacksScopesOfEventAndCategory.Average(f => f.Grade).ToString());
                    }
                    else
                    {
                        FeedbackAveragePerCategory.Add("No hay evaluaciones todavía");
                    }
                }
            }
            
            ViewBag.permision = false;

            var conferenceVersion = await _context.ConferenceVersions.FindAsync(@foodService.ConferenceVersionId);
            var bigConference = await _context.Conferences.FindAsync(conferenceVersion.ConferenceId);
            var adminList = await _context.Admins.Where(x => x.UserId == currentUserId).ToListAsync();
            if (adminList.Count > 0)
            {
                ViewBag.permision = true;
            }

            if (bigConference.OrganizerId == currentUserId)
            {
                ViewBag.permision = true;
            }
            var organizer = await _context.Users.FindAsync(bigConference.OrganizerId);
            ViewBag.organizer = organizer;

            ViewBag.feedback = await _context.Feedbacks.FirstOrDefaultAsync(f => f.UserId == currentUserId && f.EventId == @foodService.Id);

            ViewBag.menus = menus;
            ViewBag.roomName = room.Name;
            ViewBag.centreName = centre.Name;
            ViewBag.location = centre.Location;
            ViewBag.version = version;
            ViewBag.conference = conference;
            ViewBag.assistants = assistants;
            ViewBag.sponsors = sponsors;
            ViewBag.EventAssistance = EventAssistance;
            ViewBag.FeedbackCategoryName = FeedbackCategoryName;
            ViewBag.FeedbackAveragePerCategory = FeedbackAveragePerCategory;
            
            var isOrganizer = currentUserId == conference.OrganizerId;
            ViewBag.isOrganizer = isOrganizer;
            
            var admin = await _context.Admins.FirstOrDefaultAsync(x => x.UserId == currentUserId);
            var isAdmin = admin != null;
            ViewBag.isAdmin = isAdmin;

            return View(foodService);
        }

        // GET: FoodService/Create
        public async Task<IActionResult> Create(int? conferenceVersionId)
        {
            var conferenceVersions = conferenceVersionId == null
                ? await _context.ConferenceVersions.ToListAsync()
                : await _context.ConferenceVersions.Where(x => x.Id == conferenceVersionId).ToListAsync();

            var rooms = await _context.Rooms.Where(x => x.EventCentreId == conferenceVersions[0].EventCentreId).ToListAsync();

            List<object> versions = new List<object>();
            foreach (var member in conferenceVersions)
                versions.Add( new {
                    Id = member.Id,
                    Name = (await _context.Conferences.FindAsync(member.ConferenceId)).Name + " (versión " + member.Number + ")"
                } );
            this.ViewData["ConferenceVersions"] = new SelectList(versions, "Id", "Name");

            this.ViewData["CategoryOptions"] = new List<SelectListItem>
            {
                new SelectListItem {Text = "Almuerzo", Value = "lunch"},
                new SelectListItem {Text = "Cena", Value = "dinner"},
                new SelectListItem {Text = "Otro", Value = "other"}
            };
            this.ViewData["Rooms"] = new SelectList(rooms, "Id", "Name");
            return View();
        }
        public async Task<IActionResult> RemoveAssistant(int eventId)
        {

            var currentUserId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var assistants = await _context.Roles.Where(x => (x.UserId == currentUserId && x.EventId == eventId && x.Name == "attendant")).ToListAsync();
            _context.Roles.RemoveRange(assistants);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Details), new { id = eventId.ToString() });

        }
        public async Task<IActionResult> AddAssistant(int eventId)
        {
            var currentUserId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var @thisEvent = await _context.Events.FirstOrDefaultAsync(m => m.Id == eventId);
            var isOccupied = 0;

            var room = await _context.Rooms.FirstOrDefaultAsync(m => m.Id == @thisEvent.RoomId);
            var capacityUsed = await _context.Roles.Where(x => (x.EventId == eventId && x.Name == "attendant")).ToListAsync();

            if (room.MaxCapacity <= capacityUsed.Count)
            {
                TempData["AssistError"] = "Se ha alcanzado la capacidad máxima para este evento";
                isOccupied = 1;
            }
            else
            {
                var assistingToEvents = await _context.Roles.Where(x => (x.UserId == currentUserId && x.Name == "attendant")).ToListAsync();
                foreach (var aRole in assistingToEvents)
                {
                    var @event = await _context.Events.FirstOrDefaultAsync(m => m.Id == aRole.EventId);
                    if (@event.StartDate <= @thisEvent.StartDate && @event.EndDate >= @thisEvent.StartDate )
                    {
                        isOccupied = 1;
                    }
                    else if (@event.StartDate <= @thisEvent.EndDate && @event.EndDate >= @thisEvent.EndDate )
                    {
                        isOccupied = 1;
                    }
                    else if (@event.StartDate >= @thisEvent.StartDate && @event.StartDate <= @thisEvent.EndDate )
                    {
                        isOccupied = 1;
                    }
                    else if (@event.EndDate >= @thisEvent.StartDate && @event.EndDate <= @thisEvent.EndDate )
                    {
                        isOccupied = 1;
                    }
                    if (isOccupied == 1)
                    {
                        TempData["AssistError"] = "Tienes tope de horario con este evento";
                        break;
                    }
                }
            }

            if (isOccupied == 0)
            {
                var role = new Role() {UserId = currentUserId, EventId = eventId};
                _context.Add(role);
                await _context.SaveChangesAsync();
            }

ConferenceApp/Views/FoodService/Create.cshtml
@model ConferenceApp.Models.FoodService

@{
    ViewData["Title"] = "Nueva Comida";
}

<h1>Nueva Comida</h1>

<h4>Info</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Nombre</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label">Categoría</label>
                <select asp-for="Category" class="form-control" asp-items="ViewBag.CategoryOptions"></select>
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label">Inicio</label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label">Fin</label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConferenceVersionId" class="control-label">Conferencia</label>
                <select asp-for="ConferenceVersionId" class ="form-control" asp-items="ViewBag.ConferenceVersions"></select>
            </div>
            <div class="form-group">
                <label asp-for="RoomId" class="control-label">Sala</label>
                <select asp-for="RoomId" class ="form-control" asp-items="ViewBag.Rooms"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Event" asp-action="Index">Ver todos los eventos</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ConferenceApp/Views/FoodService/Delete.cshtml
@model ConferenceApp.Models.FoodService

@{
    ViewData["Title"] = "Eliminar Comida";
}

<h1>Eliminar comida</h1>

<div>
    <h4>Comida</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-controller="Event" asp-action="Index">Ver todos los eventos</a>
    </form>
</div>

ConferenceApp/Views/FoodService/Details.cshtml
@model ConferenceApp.Models.FoodService

@{
    ViewData["Title"] = "Comida";
}
@if (TempData["AssistError"] != null)
{
    <div class="alert alert-danger alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        @TempData["AssistError"]
    </div>
}

<div class="row">
    <div class="col-sm-3">Organiza: @ViewBag.organizer</div>
    <div class="col-sm-5">
        Patrocina:
        @foreach (var item in ViewBag.sponsors)
        {
            <span>@item | </span>
        }
    </div>

@if (ViewBag.permision == true)
{

    <div class="col-sm-4" style="text-align: right;">
        <a asp-controller="FoodService" asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |
        <a asp-controller="Sponsorship" asp-action="Create" asp-route-conferenceVersionId="@ViewBag.version.Id" asp-route-eventId="@Model.Id">Agregar patrocinador</a> |
        <a asp-controller="FoodService" asp-action="Delete" asp-route-id="@Model.Id">Eliminar</a>
    </div>
}
    </div>
<hr/>
<div class="row">
    <br/>
    <div class="col-sm-2">
        <img alt="calendar" src="https://cdn4.iconfinder.com/data/icons/small-n-flat/24/calendar-512.png" style="width: 150px;">
    </div>
    <div class="col-sm-6">
        <div class="row">
            <h6><b>Desde: </b>@Model.StartDate.ToString("dddd d 'de' MMMM yyyy, h:mm tt", new System.Globalization.CultureInfo("es-ES"))</h6>
        </div>
        <div class="row">
            <h6><b>Hasta: </b>@Model.EndDate.ToString("dddd d 'de' MMMM yyyy, h:mm tt", new System.Globalization.CultureInfo("es-ES"))</h6>
        </div>
        <div class="row">
            <h1>@Html.DisplayFor(model => model.Name)</h1>
        </div>
        <div class="row">
            <h5>Comida</h5>
        </div>
    </div>
    <div class="col-sm-4">
        @if (DateTime.Now > Model.EndDate)
        {
            if (ViewBag.assisting == 0)
            {
                <i>Este evento ya finalizó.</i>
            }
            else
            {
                if (ViewBag.feedback == null)
                {
                    <i>Este evento ya finalizó. Dado que asististe, puedes evaluarlo.</i>
                    <a asp-controller="Feedback" asp-action="Create" asp-route-eventId="@Model.Id" style="text-decoration: none; color: white;">
                        <button type="button" class="btn btn-primary" style="width: 100%;">Evaluar</button>
                    </a>
                }
                else
                {
                    <i>Este evento ya finalizó y mandaste tu <a asp-controller="Feedback" asp-action="Details" asp-route-id="@ViewBag.feedback.Id">evaluación</a>.</i>
                }
            }
        }
        else
        {
            @if (ViewBag.assisting == 0)
            {
                <a asp-action="AddAssistant" asp-route-eventId="@Model.Id" style="text-decoration: none; color: white;">
                    <button type="button" class="btn btn-success" style="width: 100%;">Asistir</button>
                </a>
            }
            else
            {
                <a asp-action="RemoveAssistant" asp-route-eventId="@Model.Id" style="text-decoration: none; color: white;">
                    <button type="button" class="btn btn-primary" style="width: 100%;">Dejar de asistir</button>
                </a>
            }
            <br>
            <br>
            <a asp-controller="Notification" asp-action="Create" asp-route-eventId="@Model.Id" asp-route-conferenceVersionId="@Model.ConferenceVersionId" asp-route-conferenceName="@ViewBag.conference.Name" asp-route-eventName="
@Model.Name" asp-route-conferenceVersionNumber="@ViewBag.version.Number" style="text-decoration: none; color: white;">
                <button type="button" class="btn btn-primary" style="width: 100%;">Enviar Notificacion</button>
            </a>
        }
    </div>
</div>
<hr/>
<div class="row">
    <div class="col-sm-8">
    </div>
    <div class="col-sm-4">
        @ViewBag.centreName - <a asp-controller="Room" asp-action="Details" asp-route-id="@Model.RoomId">@ViewBag.roomName</a> <br/>
        <img alt="calendar" src="https://www.connectsafely.org/wp-content/uploads/Location-pin.png" style="width: 25px;">
        @ViewBag.location
    </div>
</div>
<hr/>

<div class="row">
    <div class="col-sm-8">
        <h5>Más información</h5>
        <dl class="row">
            <dt class = "col-sm-4">
                Categoría
            </dt>
            <dd class="col-sm-8">
                @if (@Model.Category == "lunch")
                {
                    <span>Almuerzo</span>
                }
                else
                {
                    <span>Cena</span>
                }
            </dd>
            <dt class = "col-sm-4">
                Menú
            </dt>
            <dd class="col-sm-8">
                Opciones:
                <ul>
                    @foreach (var item in @ViewBag.menus)
                    {
                        <li>@item.Name (<a asp-controller="MenuOption" asp-action="Delete" asp-route-id="@item.Id">eliminar</a>)</li>
                    }
                </ul>
                <a asp-controller="MenuOption" asp-action="Create" asp-route-foodServiceId="@Model.Id">Agregar nueva opción</a>
            </dd>
        </dl>
    </div>
    <div class="col-sm-4">
        Conferencia <a asp-controller="Conference" asp-action="Details" asp-route-id="@ViewBag.conference.Id">@ViewBag.conference.Name</a>
        (versión <a asp-controller="ConferenceVersion" asp-action="Details" asp-route-id="@Model.ConferenceVersionId">@ViewBag.version.Number</a>)
    </div>
</div>
<hr/>
<div class="row">
    <div class="col-sm-8">
        <h5>Asistentes</h5>
        <dl class="row">
            <dt class = "col-sm-4">
                Cantidad
            </dt>
            <dd class = "col-sm-8">
                @ViewBag.EventAssistance
            </dd>
        </dl>
    </div>
    <div class="col-sm-4"></div>
</div>
<hr/>
<div class="row">
    <div class="col-sm-8">
        <h5>Estadísticas</h5>
        @for (var i = 0; i < ViewBag.FeedbackCategoryName.Count; i++)
        {
            <dl class="row">
                <dt class = "col-sm-4">
                    @ViewBag.FeedbackCategoryName[i]
                </dt>
                <dd class = "col-sm-8">
                    @ViewBag.FeedbackAveragePerCategory[i]
                </dd>
            </dl>
        }
    </div>
    <div class="col-sm-4"></div>
</div>

ConferenceApp/Views/FoodService/Edit.cshtml
@model ConferenceApp.Models.FoodService

@{
    ViewData["Title"] = "Editar Comida";
}

<h1>Editar</h1>

<h4>Comida</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">Nombre</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label">Categoría</label>
                <select asp-for="Category" class="form-control" asp-items="ViewBag.CategoryOptions"></select>
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label">Inicio</label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label">Fin</label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoomId" class="control-label">Sala</label>
                <select asp-for="RoomId" class ="form-control" asp-items="ViewBag.Rooms"></select>
            </div>
            <input type="hidden" asp-for="ConferenceVersionId" />
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Event" asp-action="Index">Ver todos los eventos</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ConferenceApp/Views/FoodService/Index.cshtml
@model IEnumerable<ConferenceApp.Models.FoodService>

@{
    ViewData["Title"] = "Comidas";
}

<h1>Comidas</h1>

<p>
    <a asp-action="Create">Agregar nueva</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Nombre
            </th>
            <th>
                Categoría
            </th>
            <th>
                Inicio
            </th>
            <th>
                Fin
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Ver</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>